// File generated by FlutterFire CLI.
// Firebase configuration for tahsilapp-a2eed project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc2pVgWharXqx3KnuQoPuSsPKspi_o1y8',
    appId: '1:756754492688:web:7d00acf5dbe9a5da048995',
    messagingSenderId: '756754492688',
    projectId: 'tahsilapp-a2eed',
    authDomain: 'tahsilapp-a2eed.firebaseapp.com',
    storageBucket: 'tahsilapp-a2eed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc2pVgWharXqx3KnuQoPuSsPKspi_o1y8',
    appId: '1:756754492688:android:7d00acf5dbe9a5da048995',
    messagingSenderId: '756754492688',
    projectId: 'tahsilapp-a2eed',
    storageBucket: 'tahsilapp-a2eed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc2pVgWharXqx3KnuQoPuSsPKspi_o1y8',
    appId: '1:756754492688:ios:7d00acf5dbe9a5da048995',
    messagingSenderId: '756754492688',
    projectId: 'tahsilapp-a2eed',
    storageBucket: 'tahsilapp-a2eed.appspot.com',
    iosBundleId: 'com.ta7ssil.dzlearning',
  );
}
