/// Subtitle track model for Orax Video Player
class SubtitleTrack {
  /// Display label for the subtitle track
  final String label;

  /// Language code (e.g., "en", "ar", "fr")
  final String languageCode;

  /// URL to fetch subtitle content
  final String url;

  /// Whether this is an auto-generated subtitle
  final bool isAutoGenerated;

  /// Subtitle format (e.g., "vtt", "srt")
  final String? format;

  /// Creates a SubtitleTrack instance
  const SubtitleTrack({
    required this.label,
    required this.languageCode,
    required this.url,
    this.isAutoGenerated = false,
    this.format,
  });

  /// Get language display name
  String get languageDisplayName {
    switch (languageCode.toLowerCase()) {
      case 'ar':
        return 'العربية';
      case 'en':
        return 'English';
      case 'fr':
        return 'Français';
      case 'es':
        return 'Español';
      case 'de':
        return 'Deutsch';
      case 'it':
        return 'Italiano';
      case 'pt':
        return 'Português';
      case 'ru':
        return 'Русский';
      case 'ja':
        return '日本語';
      case 'ko':
        return '한국어';
      case 'zh':
        return '中文';
      default:
        return label.isNotEmpty ? label : languageCode;
    }
  }

  @override
  String toString() => 'SubtitleTrack($label, $languageCode)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SubtitleTrack &&
        other.languageCode == languageCode &&
        other.url == url;
  }

  @override
  int get hashCode => languageCode.hashCode ^ url.hashCode;
}

/// A single subtitle cue (caption segment)
class SubtitleCue {
  /// Start time of the cue
  final Duration start;

  /// End time of the cue
  final Duration end;

  /// Text content of the cue
  final String text;

  /// Creates a SubtitleCue instance
  const SubtitleCue({
    required this.start,
    required this.end,
    required this.text,
  });

  /// Check if this cue should be displayed at the given position
  bool isActiveAt(Duration position) {
    return position >= start && position <= end;
  }

  /// Get cue duration
  Duration get duration => end - start;

  @override
  String toString() => 'SubtitleCue(${start.inSeconds}s-${end.inSeconds}s: $text)';

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SubtitleCue &&
        other.start == start &&
        other.end == end &&
        other.text == text;
  }

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ text.hashCode;
}
